### PR TITLE
fix(db): add amount column in sale table

### LINKED ISSUE #31: [DB] Add AMOUNT field to SALE table
## Objective

Add a new column `AMOUNT` to the `SALE` table to store the total amount of the sale, calculated at the time of insertion.

## Task Details

- Add column `AMOUNT` to `SALE` table:

```sql
ALTER TABLE SALE
ADD AMOUNT DECIMAL(10,2) NOT NULL DEFAULT 0;
```

## Considerations

- This value will be calculated during `SP_CREATE_SALE` and stored for performance and report efficiency.
- All future reads for sales total will rely on this stored value, avoiding costly JOINs.

### PR DESCRIPTION
**Pull request by AngelCortes2005**
### Summary
- New column in the SALE table

### Changes
- Add AMOUNT column to SALE table

### Related Issues
- Closes #31 

### Notes
- I added the AMOUNT column without the alter command because the database does not exist in production yet

### CODE REVIEW

File: scripts/001_create_tables.sql [hunk 1]
```diff
@@ -43,6 +43,7 @@ CREATE TABLE SALE (
 	ID_SALE INT IDENTITY(1,1) PRIMARY KEY,
 	[DATE] DATETIME2(0),
 	ID_USER INT,
+	AMOUNT DECIMAL(10,2) NOT NULL DEFAULT 0,
```
Comment (BrandonZamoraS) [inline scripts/001_create_tables.sql:46]: Nice way to do it

**Review by BrandonZamoraS — APPROVED** [review]
Correct implementation
